services:
  app:
    image: portfolio
    build:
      context: ./
      target: dev #dev | production 
      dockerfile: Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000"
