version: '3.8'
services:
  app:
    image: portfolio
    build:
      context: ./
      target: ${TARGET:-production} # Choose dev or production
      dockerfile: Dockerfile
    volumes:
      - .:/app      # Use in dev only
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}

