name: Node.js CI
on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Running clean install
      - run: npm ci
      - name: Building the project
      - run: npm run build --if-present
      - name: Running the nextjs project
      - run: npm start&
      - run: echo "Server is running in the background"
