name: Node.js CI
on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        # Assuming that the ssh connection from the runner to the lxc is already established 
      - name: Connect to the lxc
        run: ssh ${{secrets.REMOTE_USERNAME}}@${{secrets.REMOTE_HOST}} << 'EOF'
      - name: Clone/Pull the repo
        # Also assuming that the user github info is present in lxc already
        run: |
          if [ ! -d ${{secrets.REPO_NAME}} ]; then
              git clone https://github.com/${{secrets.USER_NAME}}/${{secrets.REPO_NAME}}.git
          else
            cd ${{secrets.REPO_NAME}}
            git pull origin main
          fi
        EOF

      - name: Test if works
        run: echo "It works!"
